import type { Metadata } from 'next';
import { Poppins } from 'next/font/google';
import './globals.css';
import Navigation from './ui/NavMenu';
import Image from 'next/image';

const poppins = Poppins({
  subsets: ['devanagari'],
  weight: '400'
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`flex ${poppins.className}`}>
        <div className="pt-4">
          <span className="flex w-full justify-center text-4xl font-extrabold text-purple mb-[96px]">
            BUYBOARD
          </span>
          <Navigation />
        </div>
        <main className="bg-grey-100 w-full h-screen"> {children}</main>
      </body>
    </html>
  );
}
