import type { Metadata } from 'next';
import { Poppins } from 'next/font/google';
import './globals.css';
import Navigation from './ui/NavMenu';

const poppins = Poppins({
  subsets: ['devanagari'],
  weight: '400'
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`flex ${poppins.className}`}>
        <Navigation />
        <main className="bg-grey-100 w-full h-screen"> {children}</main>
      </body>
    </html>
  );
}
